version: '3.8'

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
    ports:
      - 5432:5432
    networks:
      - hacknet

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - hacknet

  app:
    build: ./
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
      - redis
    ports:
      - 8081:8081
    entrypoint:
      ["./scripts/wait_for_postgres.sh", "db", "./app"]
    networks:
      - hacknet

networks:
  hacknet:
