version: '3.8'

services:
  db:
    restart: always
    image: postgres
    environment:
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    ports:
    - 5432:5432

  redis:
    image: redis:alpine
    ports:
    - 6379:6379

  migrate:
    image: migrate/migrate
    volumes:
      - ./backend/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable", "up"]
    depends_on:
      - db

  auth-app:
    build: ./backend
    environment:
    - CONFIG_PATH=${CONFIG_PATH}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_USER=${DB_USER}
    - DB_NAME=${DB_NAME}
    depends_on:
    - db
    - migrate
    - redis
    ports:
    - 8081:8081